###
POST http://localhost:3000/user/addUser
Content-Type: application/json

{
    "email": "testuer@gma2.com",
    "password": "testpassword"
}

###
POST http://localhost:3000/project/addProject
Content-Type: application/json

{
    "title": "title2",
    "description": "description",
    "period": "period",
    "technologyUsed": "technologyUsed",
    "thumbnail": "thumbnail"
}

###
DELETE http://localhost:3000/project/deleteProject
Content-Type: application/json

{
    "title": "title2"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "testuer@gma2.com",
    "password": "testpassword"
}